/* LOGIN */
export const AUTH = "AUTH";
export const LOGOUT = "LOGOUT";
/* QUIZ */
export const CREATE = "CREATE";
export const FETCH_ALL = "FETCH_ALL";
export const FETCH_ONE_QUIZ_TO_RESPONSE = "FETCH_ONE_QUIZ_TO_RESPONSE";
/* RESPONSES USER */
export const RESPONSE = "RESPONSE";
export const FETCH_ALL_USER_RESPONSES = "FETCH_ALL_USER_RESPONSES";
/* QUIZZES USER */
export const FETCH_ALL_USER_QUIZZES = "FETCH_ALL_USER_QUIZZES";
export const FETCH_ALL_QUIZZES_RESPONSE = "FETCH_ALL_QUIZZES_RESPONSE";
export const FETCH_ONE_QUIZ_TO_VIEW = "FETCH_ONE_QUIZ_TO_VIEW";
export const DELETE_QUIZ = "DELETE_QUIZ";
